language: node_js
node_js:
- 10.16.0
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_34d88e1322d3_key -iv $encrypted_34d88e1322d3_iv
  -in test.json.enc -out test.json -d
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
